import type { Metadata } from "next";
import "./globals.css";
import dynamic from "next/dynamic";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Factorbook 2.0",
  description: "Generated by create next app",
};

const ClientThemeProvider = dynamic(
  () => import("../components/ClientThemeProvider"),
  { ssr: false }
);

type LayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ClientThemeProvider>{children}</ClientThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
