version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Path to package.json
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
      include: scope
    ignore:
      - dependency-name: "next"
        versions:
          - "12.x"

  - package-ecosystem: "github-actions"
    directory: "/" # Path to GitHub Actions workflows
    schedule:
      interval: "weekly"
